#@data/values
---
service:    
  gui:
    color: green
environment:
  name: aws/front
  ingress: contour
  domain:
    internal: .micropets-supplychain.svc.cluster.local
    exposed: front.mytanzu.xyz


