apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: playlist-frontend-angular
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/name: playlist-frontend-angular
    app.kubernetes.io/part-of: musicstore
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: playlist-frontend-angular
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: akseutap6registry.azurecr.io/lsp:musicstore-dev-playlist-frontend-angular@sha256:0e09c639765b4ad4ef262b9f5543e71e8913b771c421f19f296ac16b1471f2ab
        developer.conventions/target-containers: workload
        local-source-proxy.apps.tanzu.vmware.com: akseutap6registry.azurecr.io/lsp:musicstore-dev-playlist-frontend-angular@sha256:e71fcb448a6878f102bc62d5c731f87be888758b766894f43b75705183b0383c
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/name: playlist-frontend-angular
        app.kubernetes.io/part-of: musicstore
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: playlist-frontend-angular
    spec:
      containers:
      - image: akseutap6registry.azurecr.io/library/tanzu-supply-chain/playlist-frontend-angular-musicstore-dev@sha256:e914951ff81a7dd44ee52a3e942807ef5997110932c3afe4ee2af0b746d1c9b3
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

