---
apiVersion: config.apps.tanzu.vmware.com/v1alpha4
kind: ConfigurationSource
metadata:
  name: playlist-config
spec:
  backends:
    - type: git
      uri: https://github.com/bmoussaud/micropets-app-config-gitops
      defaultLabel: main
      searchPaths:
        - config/musicstore-dev/playlist-service-springboot
---
apiVersion: config.apps.tanzu.vmware.com/v1alpha4
kind: ConfigurationSlice
metadata:
  name: playlist-config
spec:
  interval: 1s
  configurationSource: playlist-config
  content:
    - application/default
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: playlist-config
spec:
  ref:
    apiVersion: config.apps.tanzu.vmware.com/v1alpha4
    kind: ConfigurationSlice
    name: playlist-config
